# пример json ответа
x = {'current': {'cloud': 100,
                 'condition': {'text': 'Пасмурно'},
                 'feelslike_c': -7.8,
                 'is_day': 0,
                 'last_updated': '2021-12-28 18:45',
                 'last_updated_epoch': 1640706300,
                 'precip_mm': 0.0,
                 'pressure_mb': 1019.0,
                 'temp_c': -5.0,
                 'uv': 1.0,
                 'wind_kph': 0.0},
     'forecast': {'forecastday': [{'astro': {},
                                   'date': '2021-12-28',
                                   'date_epoch': 1640649600,
                                   'day': {'avgtemp_c': -12.9,
                                           'condition': {'text': 'Переохлажденный '
                                                                 'туман'},
                                           'daily_will_it_rain': 0,
                                           'daily_will_it_snow': 0,
                                           'maxtemp_c': -10.6,
                                           'maxwind_kph': 11.2,
                                           'mintemp_c': -17.8,
                                           'totalprecip_mm': 0.3},
                                   'hour': [{'cloud': 62,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -21.2,
                                             'precip_mm': 0.0,
                                             'temp_c': -17.8,
                                             'time': '2021-12-28 00:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.3},
                                            {'cloud': 68,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -21.0,
                                             'precip_mm': 0.0,
                                             'temp_c': -17.6,
                                             'time': '2021-12-28 01:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.3},
                                            {'cloud': 73,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -20.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -17.5,
                                             'time': '2021-12-28 02:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.0},
                                            {'cloud': 77,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -20.4,
                                             'precip_mm': 0.0,
                                             'temp_c': -17.3,
                                             'time': '2021-12-28 03:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.0},
                                            {'cloud': 77,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -20.2,
                                             'precip_mm': 0.0,
                                             'temp_c': -17.2,
                                             'time': '2021-12-28 04:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.0},
                                            {'cloud': 94,
                                             'condition': {'text': 'Небольшой '
                                                                   'снег'},
                                             'feelslike_c': -15.7,
                                             'precip_mm': 0.1,
                                             'temp_c': -12.4,
                                             'time': '2021-12-28 05:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 5.0},
                                            {'cloud': 90,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -15.9,
                                             'precip_mm': 0.0,
                                             'temp_c': -12.8,
                                             'time': '2021-12-28 06:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.7},
                                            {'cloud': 89,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -16.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -13.4,
                                             'time': '2021-12-28 07:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.7},
                                            {'cloud': 92,
                                             'condition': {'text': 'Небольшой '
                                                                   'снег'},
                                             'feelslike_c': -17.2,
                                             'precip_mm': 0.1,
                                             'temp_c': -14.0,
                                             'time': '2021-12-28 08:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 4.7},
                                            {'cloud': 95,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -17.9,
                                             'precip_mm': 0.0,
                                             'temp_c': -14.6,
                                             'time': '2021-12-28 09:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.7},
                                            {'cloud': 90,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -17.5,
                                             'precip_mm': 0.0,
                                             'temp_c': -14.5,
                                             'time': '2021-12-28 10:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 4.3},
                                            {'cloud': 89,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -15.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -12.3,
                                             'time': '2021-12-28 11:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 5.0},
                                            {'cloud': 79,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -14.1,
                                             'precip_mm': 0.0,
                                             'temp_c': -11.0,
                                             'time': '2021-12-28 12:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 5.0},
                                            {'cloud': 72,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -13.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -10.6,
                                             'time': '2021-12-28 13:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 5.0},
                                            {'cloud': 83,
                                             'condition': {'text': 'Небольшой '
                                                                   'снег'},
                                             'feelslike_c': -15.0,
                                             'precip_mm': 0.1,
                                             'temp_c': -11.4,
                                             'time': '2021-12-28 14:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 5.8},
                                            {'cloud': 72,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -16.1,
                                             'precip_mm': 0.0,
                                             'temp_c': -12.6,
                                             'time': '2021-12-28 15:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 5.4},
                                            {'cloud': 72,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -17.2,
                                             'precip_mm': 0.0,
                                             'temp_c': -13.1,
                                             'time': '2021-12-28 16:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 6.1},
                                            {'cloud': 67,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -16.7,
                                             'precip_mm': 0.0,
                                             'temp_c': -12.7,
                                             'time': '2021-12-28 17:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 6.1},
                                            {'cloud': 84,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -15.8,
                                             'precip_mm': 0.0,
                                             'temp_c': -11.9,
                                             'time': '2021-12-28 18:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 6.1},
                                            {'cloud': 32,
                                             'condition': {'text': 'Переохлажденный '
                                                                   'туман'},
                                             'feelslike_c': -13.1,
                                             'precip_mm': 0.0,
                                             'temp_c': -9.3,
                                             'time': '2021-12-28 19:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 6.8},
                                            {'cloud': 100,
                                             'condition': {'text': 'Дымка'},
                                             'feelslike_c': -13.7,
                                             'precip_mm': 0.0,
                                             'temp_c': -9.5,
                                             'time': '2021-12-28 20:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 7.6},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.5,
                                             'precip_mm': 0.0,
                                             'temp_c': -8.8,
                                             'time': '2021-12-28 21:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 9.0},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -8.6,
                                             'time': '2021-12-28 22:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 10.1},
                                            {'cloud': 7,
                                             'condition': {'text': 'Ясно'},
                                             'feelslike_c': -13.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -8.3,
                                             'time': '2021-12-28 23:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 11.2}]},
                                  {'astro': {},
                                   'date': '2021-12-29',
                                   'date_epoch': 1640736000,
                                   'day': {'avgtemp_c': -6.6,
                                           'condition': {'text': 'Пасмурно'},
                                           'daily_will_it_rain': 0,
                                           'daily_will_it_snow': 0,
                                           'maxtemp_c': -5.3,
                                           'maxwind_kph': 18.0,
                                           'mintemp_c': -8.5,
                                           'totalprecip_mm': 0.0},
                                   'hour': [{'cloud': 98,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -14.0,
                                             'precip_mm': 0.0,
                                             'temp_c': -8.5,
                                             'time': '2021-12-29 00:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 11.5},
                                            {'cloud': 5,
                                             'condition': {'text': 'Ясно'},
                                             'feelslike_c': -14.2,
                                             'precip_mm': 0.0,
                                             'temp_c': -8.4,
                                             'time': '2021-12-29 01:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 13.0},
                                            {'cloud': 12,
                                             'condition': {'text': 'Ясно'},
                                             'feelslike_c': -14.3,
                                             'precip_mm': 0.0,
                                             'temp_c': -8.2,
                                             'time': '2021-12-29 02:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.0},
                                            {'cloud': 48,
                                             'condition': {'text': 'Переменная '
                                                                   'облачность'},
                                             'feelslike_c': -14.4,
                                             'precip_mm': 0.0,
                                             'temp_c': -8.1,
                                             'time': '2021-12-29 03:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.1},
                                            {'cloud': 51,
                                             'condition': {'text': 'Переменная '
                                                                   'облачность'},
                                             'feelslike_c': -14.2,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.8,
                                             'time': '2021-12-29 04:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.5},
                                            {'cloud': 53,
                                             'condition': {'text': 'Переменная '
                                                                   'облачность'},
                                             'feelslike_c': -13.8,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.5,
                                             'time': '2021-12-29 05:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.5},
                                            {'cloud': 83,
                                             'condition': {'text': 'Облачно'},
                                             'feelslike_c': -13.9,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.5,
                                             'time': '2021-12-29 06:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.8},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -14.0,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.6,
                                             'time': '2021-12-29 07:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.8},
                                            {'cloud': 59,
                                             'condition': {'text': 'Переменная '
                                                                   'облачность'},
                                             'feelslike_c': -14.0,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.5,
                                             'time': '2021-12-29 08:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 16.6},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.9,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.3,
                                             'time': '2021-12-29 09:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 17.3},
                                            {'cloud': 92,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.4,
                                             'precip_mm': 0.0,
                                             'temp_c': -6.8,
                                             'time': '2021-12-29 10:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 18.0},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -12.7,
                                             'precip_mm': 0.0,
                                             'temp_c': -6.2,
                                             'time': '2021-12-29 11:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 18.0},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -12.2,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.8,
                                             'time': '2021-12-29 12:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 18.0},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.8,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.5,
                                             'time': '2021-12-29 13:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 18.0},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.4,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.3,
                                             'time': '2021-12-29 14:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 17.3},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.5,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.3,
                                             'time': '2021-12-29 15:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 17.6},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.4,
                                             'time': '2021-12-29 16:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 17.3},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.5,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.4,
                                             'time': '2021-12-29 17:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 16.9},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.3,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.4,
                                             'time': '2021-12-29 18:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 16.2},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.4,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.4,
                                             'time': '2021-12-29 19:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 16.6},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.7,
                                             'time': '2021-12-29 20:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.8},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.8,
                                             'time': '2021-12-29 21:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.1},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -11.8,
                                             'precip_mm': 0.0,
                                             'temp_c': -5.9,
                                             'time': '2021-12-29 22:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.5},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -12.0,
                                             'precip_mm': 0.0,
                                             'temp_c': -6.1,
                                             'time': '2021-12-29 23:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 15.1}]},
                                  {'astro': {},
                                   'date': '2021-12-30',
                                   'date_epoch': 1640822400,
                                   'day': {'avgtemp_c': -6.9,
                                           'condition': {'text': 'Умеренный или '
                                                                 'сильный снег'},
                                           'daily_will_it_rain': 1,
                                           'daily_will_it_snow': 0,
                                           'maxtemp_c': -6.0,
                                           'maxwind_kph': 14.8,
                                           'mintemp_c': -7.7,
                                           'totalprecip_mm': 1.8},
                                   'hour': [{'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -12.4,
                                             'precip_mm': 0.0,
                                             'temp_c': -6.5,
                                             'time': '2021-12-30 00:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.8},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -12.7,
                                             'precip_mm': 0.0,
                                             'temp_c': -6.8,
                                             'time': '2021-12-30 01:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.4},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.0,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.0,
                                             'time': '2021-12-30 02:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.8},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.1,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.1,
                                             'time': '2021-12-30 03:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.8},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.3,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.3,
                                             'time': '2021-12-30 04:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.4},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.3,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.3,
                                             'time': '2021-12-30 05:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.4},
                                            {'cloud': 100,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.4,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.5,
                                             'time': '2021-12-30 06:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.0},
                                            {'cloud': 84,
                                             'condition': {'text': 'Облачно'},
                                             'feelslike_c': -13.5,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.6,
                                             'time': '2021-12-30 07:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 13.7},
                                            {'cloud': 87,
                                             'condition': {'text': 'Облачно'},
                                             'feelslike_c': -13.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.6,
                                             'time': '2021-12-30 08:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.0},
                                            {'cloud': 78,
                                             'condition': {'text': 'Облачно'},
                                             'feelslike_c': -13.7,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.7,
                                             'time': '2021-12-30 09:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.0},
                                            {'cloud': 95,
                                             'condition': {'text': 'Пасмурно'},
                                             'feelslike_c': -13.6,
                                             'precip_mm': 0.0,
                                             'temp_c': -7.6,
                                             'time': '2021-12-30 10:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.4},
                                            {'cloud': 86,
                                             'condition': {'text': 'Сильный снег'},
                                             'feelslike_c': -12.8,
                                             'precip_mm': 0.3,
                                             'temp_c': -7.0,
                                             'time': '2021-12-30 11:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 14.0},
                                            {'cloud': 86,
                                             'condition': {'text': 'Облачно'},
                                             'feelslike_c': -12.2,
                                             'precip_mm': 0.0,
                                             'temp_c': -6.5,
                                             'time': '2021-12-30 12:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 14.0},
                                            {'cloud': 89,
                                             'condition': {'text': 'Умеренный '
                                                                   'снег'},
                                             'feelslike_c': -11.7,
                                             'precip_mm': 0.2,
                                             'temp_c': -6.2,
                                             'time': '2021-12-30 13:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 13.3},
                                            {'cloud': 95,
                                             'condition': {'text': 'Умеренный '
                                                                   'снег'},
                                             'feelslike_c': -11.3,
                                             'precip_mm': 0.1,
                                             'temp_c': -6.0,
                                             'time': '2021-12-30 14:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 13.0},
                                            {'cloud': 94,
                                             'condition': {'text': 'Умеренный '
                                                                   'снег'},
                                             'feelslike_c': -11.9,
                                             'precip_mm': 0.1,
                                             'temp_c': -6.4,
                                             'time': '2021-12-30 15:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 13.3},
                                            {'cloud': 89,
                                             'condition': {'text': 'Небольшой '
                                                                   'снег'},
                                             'feelslike_c': -12.3,
                                             'precip_mm': 0.1,
                                             'temp_c': -6.7,
                                             'time': '2021-12-30 16:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 13.3},
                                            {'cloud': 100,
                                             'condition': {'text': 'Умеренный '
                                                                   'снег'},
                                             'feelslike_c': -12.4,
                                             'precip_mm': 0.2,
                                             'temp_c': -6.9,
                                             'time': '2021-12-30 17:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 13.0},
                                            {'cloud': 96,
                                             'condition': {'text': 'Небольшой '
                                                                   'снег'},
                                             'feelslike_c': -12.3,
                                             'precip_mm': 0.0,
                                             'temp_c': -6.9,
                                             'time': '2021-12-30 18:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 12.6},
                                            {'cloud': 96,
                                             'condition': {'text': 'Умеренный '
                                                                   'снег'},
                                             'feelslike_c': -12.0,
                                             'precip_mm': 0.1,
                                             'temp_c': -6.8,
                                             'time': '2021-12-30 19:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 11.9},
                                            {'cloud': 99,
                                             'condition': {'text': 'Умеренный '
                                                                   'снег'},
                                             'feelslike_c': -12.2,
                                             'precip_mm': 0.2,
                                             'temp_c': -7.0,
                                             'time': '2021-12-30 20:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 11.5},
                                            {'cloud': 94,
                                             'condition': {'text': 'Умеренный '
                                                                   'снег'},
                                             'feelslike_c': -12.0,
                                             'precip_mm': 0.1,
                                             'temp_c': -6.9,
                                             'time': '2021-12-30 21:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 11.5},
                                            {'cloud': 98,
                                             'condition': {'text': 'Небольшой '
                                                                   'снег'},
                                             'feelslike_c': -11.7,
                                             'precip_mm': 0.0,
                                             'temp_c': -6.7,
                                             'time': '2021-12-30 22:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 0,
                                             'wind_kph': 11.2},
                                            {'cloud': 100,
                                             'condition': {'text': 'Сильный снег'},
                                             'feelslike_c': -11.3,
                                             'precip_mm': 0.4,
                                             'temp_c': -6.5,
                                             'time': '2021-12-30 23:00',
                                             'will_it_rain': 0,
                                             'will_it_snow': 1,
                                             'wind_kph': 10.8}]}]},
     'location': {'country': 'Russia',
                  'lat': 59.89,
                  'localtime': '2021-12-28 18:52',
                  'localtime_epoch': 1640706722,
                  'lon': 30.26,
                  'name': 'Saint Petersburg',
                  'region': 'Saint Petersburg City',
                  'tz_id': 'Europe/Moscow'}}
